import {
  TimeZoneClient as TimeZoneGeneratedClient,
  TimeZoneDto
} from "./autogeneratedclients/TimeZoneManagerClient";
export type TimeZoneDto = TimeZoneDto;

export class TimeZoneClient {
  private readonly client: TimeZoneGeneratedClient;

  public constructor() {
    this.client = new TimeZoneGeneratedClient();
  }

  public load(filter: string): Promise<Array<TimeZoneDto>> {
    return filter ? this.client.findByName(filter) : this.client.loadAll();
  }

  public create(timeZone: TimeZoneDto): Promise<TimeZoneDto> {
    return this.client.create(timeZone);
  }

  public update(timeZone: TimeZoneDto): Promise<TimeZoneDto> {
    return this.client.update(timeZone);
  }

  public delete(key: string): Promise<void> {
    return this.client.delete(key);
  }
}
