import {
  UserClient as UserGeneratedClient,
  UserDto,
  FullUserDto
} from "./autogeneratedclients/TimeZoneManagerClient";
export type UserDto = UserDto;
export type FullUserDto = FullUserDto;

export class UserClient {
  private readonly client: UserGeneratedClient;

  public constructor() {
    this.client = new UserGeneratedClient();
  }

  public load(filter: string): Promise<Array<UserDto>> {
    return filter ? this.client.findByName(filter) : this.client.loadAll();
  }

  public register(user: FullUserDto): Promise<UserDto> {
    return this.client.register(user);
  }

  public create(user: FullUserDto): Promise<UserDto> {
    return this.client.create(user);
  }

  public update(user: UserDto): Promise<UserDto> {
    return this.client.update(user);
  }

  public delete(key: string): Promise<void> {
    return this.client.delete(key);
  }
}
