using AutoMapper;

namespace TimeZoneManager.MappingProfiles
{
    public class BaseMapperProfile : Profile
    {
        public BaseMapperProfile()
        {
            RecognizePrefixes("AutoGenerated");
            RecognizeDestinationPrefixes("AutoGenerated");
            AddGlobalIgnore("Id");
        }
    }
}
