import { MuiThemeProvider } from "@material-ui/core";
import Layout from "./components/Layout";
import { Route } from "react-router";
import { ExistingPages } from "./ExistingPages";
import Home from "./components/Home";
import Login from "./components/Login";
import Logout from "./components/Logout";
import Users from "./components/Users";
import TimeZones from "./components/TimeZones";
import * as React from 'react';
import { AuthRoute } from "./components/AuthRoute";
import { PermissionName } from "./server/autogeneratedclients/TimeZoneManagerClient";
import Register from "./components/Register";

import theme from './formcontrols/theme';

export default () => (
    <MuiThemeProvider theme={theme}>
        <Layout>
            <AuthRoute exact path={ExistingPages.users} component={Users} permissions={[PermissionName.UserRead]} />
            <AuthRoute exact path={ExistingPages.timezones} component={TimeZones} permissions={[PermissionName.TimeZoneRead]} />
            <Route exact path={ExistingPages.logout} component={Logout} />
            <Route exact path={ExistingPages.register} component={Register} />
            <Route exact={true} path={ExistingPages.home} component={Home} permissions={[' ']} />
            <Route exact path={ExistingPages.login} component={Login} />
        </Layout>
    </MuiThemeProvider>);